---
name: "test"
description: "if query from etl, route to etl group"
condition: "request.getHeader(\"X-Trino-Catalog\") == \"uptycs\" && (request.getHeader(\"X-Trino-User\") == \"uptycs\" )"
actions:
  - "result.put(\"routingGroup\", \"etl\")"
---
name: "test1"
description: "if query from dev, route to dev group"
condition: "request.getHeader(\"X-Trino-Catalog\") == \"uptycs1\" && (request.getHeader(\"X-Trino-User\") == \"upt_read_app1\" )"
actions:
  - "result.put(\"routingGroup\", \"test\")"
